name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List all files
      run : ls -a
    - name : what is in the target folder
      run : ls -a target
    - name : what is the reports folder
      run : ls -a reports   
      
    - name: ExtentReports Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
           # Artifact name
           name: ExtentReport
           # A file, directory or wildcard pattern that describes what to upload
           path: reports 
           
    - name: Send mail
      uses: dawidd6/action-send-mail@v4>  
      with:  
        server_address: ${{secrets.EMAIL_SERVER_ADDRESS}}
        # Server port, default 25:
        server_port: ${{secrets.EMAIL_SERVER_PORT}}
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.EMAIL_ADDRESS}}
        # Optional (recommended) mail server password:
        password: ${{secrets.EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: restpostman1@gmail.com
        # Required sender full name (address can be skipped):
        from: ${{secrets.EMAIL_ADDRESS}}
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
     
        # Optional attachments:
        attachments: reports
      
